Configure weeks to start on Sunday
marcusolsson/obsidian-projects pull request #157
Opened 2022-11-17 04:50 UTC by GamerGirlandCo

closes #116

2022-11-17 06:45 UTC, marcusolsson requested changes
Thank you for this!

This seems to use Sunday as the default which would cause all existing users to switch, whether they wanted to or not. I'd prefer to keep the current behavior default to avoid frustration.

I tried it briefly and it seemed to have some trouble updating the locale initially. I had to switch a couple of times before it starting working. Will do some more testing.

Also, I think I need to reconsider putting the settings in the toolbar. It's starting to get a little cluttered with all the settings. Could you move the dropdown to the settings group on the right-hand side, to at least keep it consistent for now?

2022-11-17 06:45 UTC, marcusolsson commented on src/lib/stores/i18n.ts
> +              name: "Start Week On",
```suggestion
              name: "Start week on",
```

UI uses sentence casing.

2022-11-17 06:45 UTC, marcusolsson commented on src/views/Calendar/CalendarView.svelte
> +  // $: dayjs.Ls[dayjs.locale()]!.weekStart = weekStart == "sunday" ? 0 : 1
Remove commented line.

2022-11-19 03:35 UTC, GamerGirlandCo commented
closing this and creating a new one since my new commits aren't showing.

2022-11-19 03:35 UTC, closed without merging