Timeline view
marcusolsson/obsidian-projects pull request #178
Opened 2022-11-21 04:21 UTC by GamerGirlandCo

very much still a work in progress. please let me know what to fix!
and yes, i am very much aware of the absolute decrepit state of the code rn, but i haven't the slightest idea how to fix it. any help in that regard would be appreciated!!

**TODO**
- [ ] make it so that resizing items changes the respective start and end date
- [ ] reschedule on item move

2022-12-04 23:54 UTC, marcusolsson requested changes

2022-12-04 23:54 UTC, marcusolsson commented on src/views/Timeline/TimelineView.svelte
> +  function asOptionalBoolean(value: OptionalDataValue): boolean | Optional {
```suggestion
  function asOptionalBoolean(value: Optional<DataValue>): boolean | Optional {
```

Changed this to be more generic.

2023-03-03 21:04 UTC, brush701 commented
Curious if work is still ongoing here. Looks like the last commit is missing `src/types.ts` from which `ProjectDefinition` is imported, though that file is present in @GamerGirlandCo's fork.

2023-03-27 13:41 UTC, ltroj commented
I have no idea if this is helpful in any way, but I just learned about [markwhen](https://markwhen.com/) which can convert markdown syntax to a gantt chart/timeline view. The [markwhen renderer](https://github.com/mark-when/markwhen) seems to be open source.

2023-09-04 07:45 UTC, closed without merging